on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/sync.yml'
  schedule:
    - cron: '0 * * * *'
name: Sync
jobs:
  sync:
    uses: r-universe-org/workflows/.github/workflows/sync.yml@v3
    secrets: inherit
